name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: gradle/gradle-build-action@v2.4.2
      - name: Validate
        run: ./gradlew check validatePlugins --continue
      - name: Integration Test
        run: ./gradlew integrationTest --info

